# Generated by Django 6.1.1 on 2026-09-17 19:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la boutique')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Montant (FCFA)')),
                ('methode', models.CharField(default='TMoney', max_length=50, verbose_name='Méthode de paiement')),
                ('reference_paiement', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence TMoney')),
                ('telephone_paiement', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro TMoney utilisé')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('en_attente', 'En attente')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='gestion.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('gerant', 'Gérant'), ('vendeur', 'Vendeur')], default='gerant', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro de téléphone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('boutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='gestion.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('categorie', models.CharField(blank=True, default='Général', max_length=100, verbose_name='Catégorie')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat (FCFA)")),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de vente (FCFA)')),
                ('quantite_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('seuil_alerte', models.IntegerField(default=2, verbose_name="Seuil d'alerte de rupture")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='gestion.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
                'unique_together': {('boutique', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rupture_stock', 'Rupture de stock proche'), ('abonnement', 'Abonnement'), ('info', 'Information')], default='rupture_stock', max_length=50, verbose_name='Type de notification')),
                ('message', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gestion.boutique', verbose_name='Boutique')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='gestion.produit', verbose_name='Produit concerné')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité achetée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix unitaire d'achat (FCFA)")),
                ('fournisseur', models.CharField(blank=True, default='', max_length=200, verbose_name='Fournisseur')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='gestion.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité vendue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire de vente (FCFA)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de vente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='gestion.produit', verbose_name='Produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur / Enregistré par')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date'],
            },
        ),
    ]
