# Generated by Django 6.1.1 on 2026-09-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Photo du produit'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('gerant', 'Gérant'), ('employe', 'Employé'), ('vendeur', 'Employé')], default='gerant', max_length=20, verbose_name='Rôle'),
        ),
    ]
