# Generated by Django 6.1.1 on 2026-09-18 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_produit_image_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='compte_actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('gerant', 'Gérant'), ('employe', 'Employé'), ('vendeur', 'Employé')], default='gerant', max_length=20, verbose_name='Rôle'),
        ),
        migrations.CreateModel(
            name='JournalActionSuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action effectuée')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date et heure de l'action")),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('boutique_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_super_admin', to='gestion.boutique', verbose_name='Boutique cible')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_super_admin', to=settings.AUTH_USER_MODEL, verbose_name='Super-Administrateur')),
            ],
            options={
                'verbose_name': 'Journal Action Super-Admin',
                'verbose_name_plural': 'Journal Actions Super-Admin',
                'ordering': ['-date_action'],
            },
        ),
    ]
