# Generated by Django 6.1.1 on 2026-09-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_boutique_compte_actif_alter_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='methode_paiement',
            field=models.CharField(choices=[('TMoney', 'TMoney (Togocom)'), ('Flooz', 'Moov Flooz')], default='TMoney', max_length=20, verbose_name='Moyen de paiement mobile'),
        ),
        migrations.AddField(
            model_name='vente',
            name='prix_achat_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat unitaire au moment de la vente (FCFA)"),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='reference_paiement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Référence TMoney / Flooz'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='telephone_paiement',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro de paiement utilisé'),
        ),
    ]
