# Generated by Django 6.1.1 on 2026-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_abonnement_methode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_modification_mdp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière modification du mot de passe'),
        ),
    ]
