# Generated by Django 6.1.1 on 2026-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_utilisateur_date_modification_mdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='boutiques_gerees',
            field=models.ManyToManyField(blank=True, related_name='administrateurs', to='gestion.boutique', verbose_name='Boutiques gérées'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('administrateur', 'Administrateur'), ('gerant', 'Gérant'), ('employe', 'Employé'), ('vendeur', 'Employé')], default='gerant', max_length=20, verbose_name='Rôle'),
        ),
    ]
