# Generated by Django 6.1.1 on 2026-09-19 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_utilisateur_boutiques_gerees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destine_a_tous', models.BooleanField(default=True, verbose_name="Destiné à toute l'équipe")),
                ('type_message', models.CharField(choices=[('normal', 'Message standard'), ('consigne', "Consigne d'équipe"), ('urgent', 'Important / Urgent')], default='normal', max_length=20, verbose_name='Type de message')),
                ('titre', models.CharField(blank=True, default='', max_length=200, verbose_name='Titre ou Sujet')),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_internes', to='gestion.boutique', verbose_name='Boutique')),
                ('destinataire', models.ForeignKey(blank=True, help_text='Laisser vide si le message est destiné à tous les employés de la boutique', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name="Destinataire (vide si toute l'équipe)")),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('lu_par', models.ManyToManyField(blank=True, related_name='messages_lus', to=settings.AUTH_USER_MODEL, verbose_name='Lu par')),
            ],
            options={
                'verbose_name': 'Message Interne Boutique',
                'verbose_name_plural': 'Messages Internes Boutique',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
